import { emptyBallColor, whiteBallColor, blackBallColor } from "./colors balls";


// The all levels in the game.
export const objectGame = {
  1: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
  ],
  2: [
    [whiteBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
  ],
  3: [
    [emptyBallColor, blackBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  4: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
  ],
  5: [
    [blackBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  6: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  7: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
  ],
  8: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor, emptyBallColor],
  ],
  9: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  10: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  11: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [blackBallColor, whiteBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
  ],
  12: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
  ],
  13: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [blackBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  14: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
  ],
  15: [
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [blackBallColor, whiteBallColor, emptyBallColor],
  ],
  16: [
    [whiteBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor],
    [emptyBallColor, emptyBallColor, emptyBallColor],
  ],
  17: [
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor, emptyBallColor],
  ],
  18: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  19: [
    [blackBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
  ],
  20: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [blackBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  21: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
  ],
  22: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  23: [
    [emptyBallColor, whiteBallColor, blackBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  24: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
  ],
  25: [
    [emptyBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
  ],
  26: [
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  27: [
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  28: [
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, whiteBallColor],
  ],
  29: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  30: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
  ],
  31: [
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, blackBallColor],
  ],
  32: [
    [whiteBallColor, whiteBallColor, blackBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
  ],
  33: [
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
  ],
  34: [
    [emptyBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
  ],
  35: [
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [blackBallColor, emptyBallColor, whiteBallColor],
  ],
  36: [
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, blackBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
  ],
  37: [
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, blackBallColor],
  ],
  38: [
    [whiteBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, emptyBallColor, whiteBallColor],
  ],
  39: [
    [blackBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, emptyBallColor],
  ],
  40: [
    [emptyBallColor, whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  41: [
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
  ],
  42: [
    [whiteBallColor, emptyBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  43: [
    [whiteBallColor, whiteBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [emptyBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [emptyBallColor, whiteBallColor, whiteBallColor],
  ],
  44: [
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, blackBallColor, emptyBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, emptyBallColor],
  ],
  45: [
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor],
    [blackBallColor, whiteBallColor, emptyBallColor],
  ],
  46: [
    [blackBallColor, whiteBallColor, whiteBallColor],
    [emptyBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
  ],
  47: [
    [whiteBallColor, blackBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor, whiteBallColor],
    [whiteBallColor, whiteBallColor],
    [whiteBallColor, emptyBallColor, whiteBallColor],
  ],
};
